Building DAG of jobs...
Singularity image location: /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	add_uns_to_h5ad
	1	all
	1	get_count_matrix
	1	run_analysis
	4
Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (1):
	get_count_matrix
Selected jobs (1):
	get_count_matrix
Resources after job selection: {'_cores': 3, '_nodes': 9223372036854775806}

[Tue Nov  3 21:42:47 2020]
rule get_count_matrix:
    input: bus_out/correct_output.bus
    output: counts.RData
    log: logs/get_count_matrix.log
    jobid: 3
    benchmark: benchmarks/get_count_matrix.txt

 singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768  --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg sh -c 'type conda'
 singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768  --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg sh -c 'conda --version'
 singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768  --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg sh -c 'conda info --json'
 singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768  --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg sh -c 'type conda'
 singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768  --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg sh -c 'conda --version'
 singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768  --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg sh -c 'conda info --json'
 singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768 --bind /scratch/mfiruleva/winter/genomes/mus:/home --bind /scratch/mfiruleva/GSEs_processing/wget_and_process:/files --bind /mnt/tank/scratch/mfiruleva/scn/config/65ef9760:/mnt/tank/scratch/mfiruleva/scn/config/65ef9760 --bind /mnt/tank/scratch/mfiruleva/scn/stats/summary.csv:/mnt/tank/scratch/mfiruleva/scn/stats/summary.csv --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg bash -c 'source /opt/conda/bin/activate '\''/mnt/tank/scratch/mfiruleva/scn/config/65ef9760'\''; set -euo pipefail;  Rscript scripts/get_count_matrix.R 2> logs/get_count_matrix.log'
Activating singularity image /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg
Activating conda environment: /mnt/tank/scratch/mfiruleva/scn/config/65ef9760
Full Traceback (most recent call last):
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/executors.py", line 2078, in run_wrapper
    run(
  File "/mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768/rules/get_counts.smk", line 28, in __rule_get_count_matrix
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/shell.py", line 176, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768 --bind /scratch/mfiruleva/winter/genomes/mus:/home --bind /scratch/mfiruleva/GSEs_processing/wget_and_process:/files --bind /mnt/tank/scratch/mfiruleva/scn/config/65ef9760:/mnt/tank/scratch/mfiruleva/scn/config/65ef9760 --bind /mnt/tank/scratch/mfiruleva/scn/stats/summary.csv:/mnt/tank/scratch/mfiruleva/scn/stats/summary.csv --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg bash -c 'source /opt/conda/bin/activate '\''/mnt/tank/scratch/mfiruleva/scn/config/65ef9760'\''; set -euo pipefail;  Rscript scripts/get_count_matrix.R 2> logs/get_count_matrix.log'' returned non-zero exit status 1.

[Tue Nov  3 21:43:48 2020]
Error in rule get_count_matrix:
    jobid: 3
    output: counts.RData
    log: logs/get_count_matrix.log (check log file(s) for error message)
    conda-env: /mnt/tank/scratch/mfiruleva/scn/config/65ef9760
    shell:
        Rscript scripts/get_count_matrix.R 2> logs/get_count_matrix.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/executors.py", line 2078, in run_wrapper
    run(
  File "/mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768/rules/get_counts.smk", line 28, in __rule_get_count_matrix
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/shell.py", line 176, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768 --bind /scratch/mfiruleva/winter/genomes/mus:/home --bind /scratch/mfiruleva/GSEs_processing/wget_and_process:/files --bind /mnt/tank/scratch/mfiruleva/scn/config/65ef9760:/mnt/tank/scratch/mfiruleva/scn/config/65ef9760 --bind /mnt/tank/scratch/mfiruleva/scn/stats/summary.csv:/mnt/tank/scratch/mfiruleva/scn/stats/summary.csv --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg bash -c 'source /opt/conda/bin/activate '\''/mnt/tank/scratch/mfiruleva/scn/config/65ef9760'\''; set -euo pipefail;  Rscript scripts/get_count_matrix.R 2> logs/get_count_matrix.log'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/executors.py", line 493, in _callback
    raise ex
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/executors.py", line 479, in cached_or_run
    run_func(*args)
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/executors.py", line 2160, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 11 of /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768/rules/get_counts.smk:
Command ' singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768 --bind /scratch/mfiruleva/winter/genomes/mus:/home --bind /scratch/mfiruleva/GSEs_processing/wget_and_process:/files --bind /mnt/tank/scratch/mfiruleva/scn/config/65ef9760:/mnt/tank/scratch/mfiruleva/scn/config/65ef9760 --bind /mnt/tank/scratch/mfiruleva/scn/stats/summary.csv:/mnt/tank/scratch/mfiruleva/scn/stats/summary.csv --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg bash -c 'source /opt/conda/bin/activate '\''/mnt/tank/scratch/mfiruleva/scn/config/65ef9760'\''; set -euo pipefail;  Rscript scripts/get_count_matrix.R 2> logs/get_count_matrix.log'' returned non-zero exit status 1.
  File "/mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768/rules/get_counts.smk", line 11, in __rule_get_count_matrix

RuleException:
CalledProcessError in line 11 of /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768/rules/get_counts.smk:
Command ' singularity exec --home /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768 --bind /scratch/mfiruleva/winter/genomes/mus:/home --bind /scratch/mfiruleva/GSEs_processing/wget_and_process:/files --bind /mnt/tank/scratch/mfiruleva/scn/config/65ef9760:/mnt/tank/scratch/mfiruleva/scn/config/65ef9760 --bind /mnt/tank/scratch/mfiruleva/scn/stats/summary.csv:/mnt/tank/scratch/mfiruleva/scn/stats/summary.csv --bind /nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages:/mnt/snakemake /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg bash -c 'source /opt/conda/bin/activate '\''/mnt/tank/scratch/mfiruleva/scn/config/65ef9760'\''; set -euo pipefail;  Rscript scripts/get_count_matrix.R 2> logs/get_count_matrix.log'' returned non-zero exit status 1.
  File "/mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768/rules/get_counts.smk", line 11, in __rule_get_count_matrix
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/tank/scratch/mfiruleva/scn/data/GSE154817/SRS7052768/.snakemake/log/2020-11-03T214246.736150.snakemake.log
unlocking
removing lock
removing lock
removed all locks
