Building DAG of jobs...
Singularity image location: /mnt/tank/scratch/mfiruleva/scn/config/e78b32002e592105c700c757fbe8a8e4.simg
Creating conda environment /mnt/tank/scratch/mfiruleva/scn/config/5d179225.yaml...
Downloading and installing remote packages.
Full Traceback (most recent call last):
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 299, in create
    out = shell.check_output(cmd, stderr=subprocess.STDOUT)
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/shell.py", line 44, in check_output
    return sp.check_output(
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'conda env create --file '/mnt/tank/scratch/mfiruleva/scn/config/c58701e4.yaml' --prefix '/mnt/tank/scratch/mfiruleva/scn/config/c58701e4'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/__init__.py", line 580, in snakemake
    success = workflow.execute(
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/workflow.py", line 789, in execute
    dag.create_conda_envs(
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/dag.py", line 265, in create_conda_envs
    env.create(dryrun)
  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 318, in create
    raise CreateCondaEnvironmentException(
snakemake.exceptions.CreateCondaEnvironmentException: Could not create conda environment from /mnt/tank/scratch/mfiruleva/scn/config/5d179225.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
libseccomp-2.4.1     | 179 KB    |            |   0% libseccomp-2.4.1     | 179 KB    | 8          |   9% libseccomp-2.4.1     | 179 KB    | ########## | 100% 
llvm-tools-9.0.1     | 4.9 MB    |            |   0% llvm-tools-9.0.1     | 4.9 MB    |            |   0% llvm-tools-9.0.1     | 4.9 MB    | 3          |   4% llvm-tools-9.0.1     | 4.9 MB    | #          |  11% llvm-tools-9.0.1     | 4.9 MB    | #9         |  19% llvm-tools-9.0.1     | 4.9 MB    | ###2       |  33% llvm-tools-9.0.1     | 4.9 MB    | ####4      |  45% llvm-tools-9.0.1     | 4.9 MB    | #####3     |  53% llvm-tools-9.0.1     | 4.9 MB    | #########3 |  94% llvm-tools-9.0.1     | 4.9 MB    | ########## | 100% 
aiohttp-3.6.2        | 622 KB    |            |   0% aiohttp-3.6.2        | 622 KB    | 2          |   3% aiohttp-3.6.2        | 622 KB    | ##8        |  28% aiohttp-3.6.2        | 622 KB    | ########## | 100% 
graphviz-2.42.3      | 7.3 MB    |            |   0% graphviz-2.42.3      | 7.3 MB    |            |   0% graphviz-2.42.3      | 7.3 MB    | #####9     |  59% graphviz-2.42.3      | 7.3 MB    | #######    |  70% graphviz-2.42.3      | 7.3 MB    | ########4  |  84% graphviz-2.42.3      | 7.3 MB    | #########4 |  94% graphviz-2.42.3      | 7.3 MB    | ########## | 100% 
lz4-c-1.9.2          | 203 KB    |            |   0% lz4-c-1.9.2          | 203 KB    | 7          |   8% lz4-c-1.9.2          | 203 KB    | #######8   |  79% lz4-c-1.9.2          | 203 KB    | ########## | 100% 
atk-1.0-2.36.0       | 523 KB    |            |   0% atk-1.0-2.36.0       | 523 KB    | 3          |   3% atk-1.0-2.36.0       | 523 KB    | ########## | 100% 
r-praise-1.0.0       | 23 KB     |            |   0% r-praise-1.0.0       | 23 KB     | ######8    |  69% r-praise-1.0.0       | 23 KB     | ########## | 100% 
gfortran_impl_linux- | 9.0 MB    |            |   0% gfortran_impl_linux- | 9.0 MB    |            |   0% gfortran_impl_linux- | 9.0 MB    | 2          |   3% gfortran_impl_linux- | 9.0 MB    | 7          |   7% gfortran_impl_linux- | 9.0 MB    | #2         |  13% gfortran_impl_linux- | 9.0 MB    | #8         |  19% gfortran_impl_linux- | 9.0 MB    | ##4        |  24% gfortran_impl_linux- | 9.0 MB    | ##8        |  28% gfortran_impl_linux- | 9.0 MB    | ###5       |  36% gfortran_impl_linux- | 9.0 MB    | ####       |  40% gfortran_impl_linux- | 9.0 MB    | #####      |  51% gfortran_impl_linux- | 9.0 MB    | #####7     |  57% gfortran_impl_linux- | 9.0 MB    | ######5    |  65% gfortran_impl_linux- | 9.0 MB    | #######1   |  71% gfortran_impl_linux- | 9.0 MB    | #######8   |  79% gfortran_impl_linux- | 9.0 MB    | ########5  |  85% gfortran_impl_linux- | 9.0 MB    | #########  |  91% gfortran_impl_linux- | 9.0 MB    | #########9 |  99% gfortran_impl_linux- | 9.0 MB    | ########## | 100% 
r-ape-5.4_1          | 2.2 MB    |            |   0% r-ape-5.4_1          | 2.2 MB    |            |   1% r-ape-5.4_1          | 2.2 MB    | ##2        |  23% r-ape-5.4_1          | 2.2 MB    | #####5     |  56% r-ape-5.4_1          | 2.2 MB    | ######9    |  69% r-ape-5.4_1          | 2.2 MB    | ########5  |  86% r-ape-5.4_1          | 2.2 MB    | ########## | 100% 
r-kernsmooth-2.23_17 | 104 KB    |            |   0% r-kernsmooth-2.23_17 | 104 KB    | #5         |  15% r-kernsmooth-2.23_17 | 104 KB    | ########## | 100% 
fftw-3.3.8           | 3.9 MB    |            |   0% fftw-3.3.8           | 3.9 MB    |            |   0% fftw-3.3.8           | 3.9 MB    | 7          |   8% fftw-3.3.8           | 3.9 MB    | ##3        |  24% fftw-3.3.8           | 3.9 MB    | ##9        |  29% fftw-3.3.8           | 3.9 MB    | ###4       |  34% fftw-3.3.8           | 3.9 MB    | #####1     |  52% fftw-3.3.8           | 3.9 MB    | ######8    |  69% fftw-3.3.8           | 3.9 MB    | #########1 |  92% fftw-3.3.8           | 3.9 MB    | ########## | 100% 
libopenblas-0.3.10   | 7.8 MB    |            |   0% libopenblas-0.3.10   | 7.8 MB    |            |   0% libopenblas-0.3.10   | 7.8 MB    | 2          |   2% libopenblas-0.3.10   | 7.8 MB    | 8          |   8% libopenblas-0.3.10   | 7.8 MB    | ##         |  20% libopenblas-0.3.10   | 7.8 MB    | ##5        |  26% libopenblas-0.3.10   | 7.8 MB    | ###        |  31% libopenblas-0.3.10   | 7.8 MB    | ###8       |  38% libopenblas-0.3.10   | 7.8 MB    | ####4      |  44% libopenblas-0.3.10   | 7.8 MB    | #####1     |  51% libopenblas-0.3.10   | 7.8 MB    | ######     |  60% libopenblas-0.3.10   | 7.8 MB    | ######8    |  68% libopenblas-0.3.10   | 7.8 MB    | #######8   |  78% libopenblas-0.3.10   | 7.8 MB    | ########6  |  86% libopenblas-0.3.10   | 7.8 MB    | #########3 |  94% 

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base conda


WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /nfs/home/mfiruleva/anaconda3/pkgs/libopenblas-0.3.10-h5a2b251_0/lib/.nfs00000000002f008000000445.  Please remove this file manually (you may need to reboot to free file handles)
libopenblas-0.3.10   | 7.8 MB    | ########## | 100% 
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 698, in _execute_actions
        extract_axn.execute(progress_update_extract_axn)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 1245, in execute
        progress_update_callback=progress_update_callback)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/create.py", line 219, in extract_tarball
        conda_package_handling.api.extract(tarball_full_path, dest_dir=destination_directory)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 58, in extract
        SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 135, in extract
        _tar_xf(fn, dest_dir)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 88, in _tar_xf
        archive_utils.extract_file(tarball)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_package_handling/archive_utils.py", line 15, in extract_file
        raise InvalidArchiveError(tarball, error_str.decode('utf-8'))
    conda_package_handling.exceptions.InvalidArchiveError: Error with archive /nfs/home/mfiruleva/anaconda3/pkgs/libopenblas-0.3.10-h5a2b251_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:
    
    Can't create 'info/recipe/parent/recipe_log.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 39, in install
        unlink_link_transaction.download_and_extract()
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 194, in download_and_extract
        self._pfe.execute()
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 649, in execute
        exc = self._execute_actions(prec_or_spec, prec_actions)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 705, in _execute_actions
        cache_axn.reverse()
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 1206, in reverse
        backoff_rename(self.hold_path, self.target_full_path, force=True)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 88, in backoff_rename
        exp_backoff_fn(rename, source_path, destination_path, force)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 25, in exp_backoff_fn
        return fn(*args, **kwargs)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 57, in rename
        os.rename(source_path, destination_path)
    FileNotFoundError: [Errno 2] No such file or directory: '/nfs/home/mfiruleva/anaconda3/pkgs/libopenblas-0.3.10-h5a2b251_0.tar.bz2.c~' -> '/nfs/home/mfiruleva/anaconda3/pkgs/libopenblas-0.3.10-h5a2b251_0.tar.bz2'

`$ /nfs/home/mfiruleva/anaconda3/bin/conda-env create --file /mnt/tank/scratch/mfiruleva/scn/config/c58701e4.yaml --prefix /mnt/tank/scratch/mfiruleva/scn/config/c58701e4`

  environment variables:
                 CIO_TEST=<not set>
                 CNI_PATH=/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/cni
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=scn_cor
                CONDA_EXE=/nfs/home/mfiruleva/anaconda3/bin/conda
             CONDA_PREFIX=/nfs/home/mfiruleva/anaconda3/envs/scn_cor
           CONDA_PREFIX_1=/nfs/home/mfiruleva/anaconda3
    CONDA_PROMPT_MODIFIER=(scn_cor)
         CONDA_PYTHON_EXE=/nfs/home/mfiruleva/anaconda3/bin/python
               CONDA_ROOT=/nfs/home/mfiruleva/anaconda3
              CONDA_SHLVL=2
               MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/shar
                          e/modules/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles
                     PATH=/nfs/home/mfiruleva/anaconda3/envs/scn_cor/bin:/nfs/home/mfiruleva/ana
                          conda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbi
                          n:/bin:/usr/games:/usr/local/games:/snap/bin:/nfs/home/mfiruleva/anaco
                          nda3/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : scn_cor
    active env location : /nfs/home/mfiruleva/anaconda3/envs/scn_cor
            shell level : 2
       user config file : /nfs/home/mfiruleva/.condarc
 populated config files : /nfs/home/mfiruleva/.condarc
          conda version : 4.8.3
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __glibc=2.27
       base environment : /nfs/home/mfiruleva/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-canary/linux-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /nfs/home/mfiruleva/anaconda3/pkgs
                          /nfs/home/mfiruleva/.conda/pkgs
       envs directories : /nfs/home/mfiruleva/anaconda3/envs
                          /nfs/home/mfiruleva/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-112-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 2178:1901
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.




CreateCondaEnvironmentException:
Could not create conda environment from /mnt/tank/scratch/mfiruleva/scn/config/5d179225.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
libseccomp-2.4.1     | 179 KB    |            |   0% libseccomp-2.4.1     | 179 KB    | 8          |   9% libseccomp-2.4.1     | 179 KB    | ########## | 100% 
llvm-tools-9.0.1     | 4.9 MB    |            |   0% llvm-tools-9.0.1     | 4.9 MB    |            |   0% llvm-tools-9.0.1     | 4.9 MB    | 3          |   4% llvm-tools-9.0.1     | 4.9 MB    | #          |  11% llvm-tools-9.0.1     | 4.9 MB    | #9         |  19% llvm-tools-9.0.1     | 4.9 MB    | ###2       |  33% llvm-tools-9.0.1     | 4.9 MB    | ####4      |  45% llvm-tools-9.0.1     | 4.9 MB    | #####3     |  53% llvm-tools-9.0.1     | 4.9 MB    | #########3 |  94% llvm-tools-9.0.1     | 4.9 MB    | ########## | 100% 
aiohttp-3.6.2        | 622 KB    |            |   0% aiohttp-3.6.2        | 622 KB    | 2          |   3% aiohttp-3.6.2        | 622 KB    | ##8        |  28% aiohttp-3.6.2        | 622 KB    | ########## | 100% 
graphviz-2.42.3      | 7.3 MB    |            |   0% graphviz-2.42.3      | 7.3 MB    |            |   0% graphviz-2.42.3      | 7.3 MB    | #####9     |  59% graphviz-2.42.3      | 7.3 MB    | #######    |  70% graphviz-2.42.3      | 7.3 MB    | ########4  |  84% graphviz-2.42.3      | 7.3 MB    | #########4 |  94% graphviz-2.42.3      | 7.3 MB    | ########## | 100% 
lz4-c-1.9.2          | 203 KB    |            |   0% lz4-c-1.9.2          | 203 KB    | 7          |   8% lz4-c-1.9.2          | 203 KB    | #######8   |  79% lz4-c-1.9.2          | 203 KB    | ########## | 100% 
atk-1.0-2.36.0       | 523 KB    |            |   0% atk-1.0-2.36.0       | 523 KB    | 3          |   3% atk-1.0-2.36.0       | 523 KB    | ########## | 100% 
r-praise-1.0.0       | 23 KB     |            |   0% r-praise-1.0.0       | 23 KB     | ######8    |  69% r-praise-1.0.0       | 23 KB     | ########## | 100% 
gfortran_impl_linux- | 9.0 MB    |            |   0% gfortran_impl_linux- | 9.0 MB    |            |   0% gfortran_impl_linux- | 9.0 MB    | 2          |   3% gfortran_impl_linux- | 9.0 MB    | 7          |   7% gfortran_impl_linux- | 9.0 MB    | #2         |  13% gfortran_impl_linux- | 9.0 MB    | #8         |  19% gfortran_impl_linux- | 9.0 MB    | ##4        |  24% gfortran_impl_linux- | 9.0 MB    | ##8        |  28% gfortran_impl_linux- | 9.0 MB    | ###5       |  36% gfortran_impl_linux- | 9.0 MB    | ####       |  40% gfortran_impl_linux- | 9.0 MB    | #####      |  51% gfortran_impl_linux- | 9.0 MB    | #####7     |  57% gfortran_impl_linux- | 9.0 MB    | ######5    |  65% gfortran_impl_linux- | 9.0 MB    | #######1   |  71% gfortran_impl_linux- | 9.0 MB    | #######8   |  79% gfortran_impl_linux- | 9.0 MB    | ########5  |  85% gfortran_impl_linux- | 9.0 MB    | #########  |  91% gfortran_impl_linux- | 9.0 MB    | #########9 |  99% gfortran_impl_linux- | 9.0 MB    | ########## | 100% 
r-ape-5.4_1          | 2.2 MB    |            |   0% r-ape-5.4_1          | 2.2 MB    |            |   1% r-ape-5.4_1          | 2.2 MB    | ##2        |  23% r-ape-5.4_1          | 2.2 MB    | #####5     |  56% r-ape-5.4_1          | 2.2 MB    | ######9    |  69% r-ape-5.4_1          | 2.2 MB    | ########5  |  86% r-ape-5.4_1          | 2.2 MB    | ########## | 100% 
r-kernsmooth-2.23_17 | 104 KB    |            |   0% r-kernsmooth-2.23_17 | 104 KB    | #5         |  15% r-kernsmooth-2.23_17 | 104 KB    | ########## | 100% 
fftw-3.3.8           | 3.9 MB    |            |   0% fftw-3.3.8           | 3.9 MB    |            |   0% fftw-3.3.8           | 3.9 MB    | 7          |   8% fftw-3.3.8           | 3.9 MB    | ##3        |  24% fftw-3.3.8           | 3.9 MB    | ##9        |  29% fftw-3.3.8           | 3.9 MB    | ###4       |  34% fftw-3.3.8           | 3.9 MB    | #####1     |  52% fftw-3.3.8           | 3.9 MB    | ######8    |  69% fftw-3.3.8           | 3.9 MB    | #########1 |  92% fftw-3.3.8           | 3.9 MB    | ########## | 100% 
libopenblas-0.3.10   | 7.8 MB    |            |   0% libopenblas-0.3.10   | 7.8 MB    |            |   0% libopenblas-0.3.10   | 7.8 MB    | 2          |   2% libopenblas-0.3.10   | 7.8 MB    | 8          |   8% libopenblas-0.3.10   | 7.8 MB    | ##         |  20% libopenblas-0.3.10   | 7.8 MB    | ##5        |  26% libopenblas-0.3.10   | 7.8 MB    | ###        |  31% libopenblas-0.3.10   | 7.8 MB    | ###8       |  38% libopenblas-0.3.10   | 7.8 MB    | ####4      |  44% libopenblas-0.3.10   | 7.8 MB    | #####1     |  51% libopenblas-0.3.10   | 7.8 MB    | ######     |  60% libopenblas-0.3.10   | 7.8 MB    | ######8    |  68% libopenblas-0.3.10   | 7.8 MB    | #######8   |  78% libopenblas-0.3.10   | 7.8 MB    | ########6  |  86% libopenblas-0.3.10   | 7.8 MB    | #########3 |  94% 

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base conda


WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /nfs/home/mfiruleva/anaconda3/pkgs/libopenblas-0.3.10-h5a2b251_0/lib/.nfs00000000002f008000000445.  Please remove this file manually (you may need to reboot to free file handles)
libopenblas-0.3.10   | 7.8 MB    | ########## | 100% 
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 698, in _execute_actions
        extract_axn.execute(progress_update_extract_axn)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 1245, in execute
        progress_update_callback=progress_update_callback)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/create.py", line 219, in extract_tarball
        conda_package_handling.api.extract(tarball_full_path, dest_dir=destination_directory)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 58, in extract
        SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 135, in extract
        _tar_xf(fn, dest_dir)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 88, in _tar_xf
        archive_utils.extract_file(tarball)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_package_handling/archive_utils.py", line 15, in extract_file
        raise InvalidArchiveError(tarball, error_str.decode('utf-8'))
    conda_package_handling.exceptions.InvalidArchiveError: Error with archive /nfs/home/mfiruleva/anaconda3/pkgs/libopenblas-0.3.10-h5a2b251_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:
    
    Can't create 'info/recipe/parent/recipe_log.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 39, in install
        unlink_link_transaction.download_and_extract()
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 194, in download_and_extract
        self._pfe.execute()
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 649, in execute
        exc = self._execute_actions(prec_or_spec, prec_actions)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 705, in _execute_actions
        cache_axn.reverse()
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 1206, in reverse
        backoff_rename(self.hold_path, self.target_full_path, force=True)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 88, in backoff_rename
        exp_backoff_fn(rename, source_path, destination_path, force)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 25, in exp_backoff_fn
        return fn(*args, **kwargs)
      File "/nfs/home/mfiruleva/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 57, in rename
        os.rename(source_path, destination_path)
    FileNotFoundError: [Errno 2] No such file or directory: '/nfs/home/mfiruleva/anaconda3/pkgs/libopenblas-0.3.10-h5a2b251_0.tar.bz2.c~' -> '/nfs/home/mfiruleva/anaconda3/pkgs/libopenblas-0.3.10-h5a2b251_0.tar.bz2'

`$ /nfs/home/mfiruleva/anaconda3/bin/conda-env create --file /mnt/tank/scratch/mfiruleva/scn/config/c58701e4.yaml --prefix /mnt/tank/scratch/mfiruleva/scn/config/c58701e4`

  environment variables:
                 CIO_TEST=<not set>
                 CNI_PATH=/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/cni
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=scn_cor
                CONDA_EXE=/nfs/home/mfiruleva/anaconda3/bin/conda
             CONDA_PREFIX=/nfs/home/mfiruleva/anaconda3/envs/scn_cor
           CONDA_PREFIX_1=/nfs/home/mfiruleva/anaconda3
    CONDA_PROMPT_MODIFIER=(scn_cor)
         CONDA_PYTHON_EXE=/nfs/home/mfiruleva/anaconda3/bin/python
               CONDA_ROOT=/nfs/home/mfiruleva/anaconda3
              CONDA_SHLVL=2
               MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/shar
                          e/modules/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles
                     PATH=/nfs/home/mfiruleva/anaconda3/envs/scn_cor/bin:/nfs/home/mfiruleva/ana
                          conda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbi
                          n:/bin:/usr/games:/usr/local/games:/snap/bin:/nfs/home/mfiruleva/anaco
                          nda3/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : scn_cor
    active env location : /nfs/home/mfiruleva/anaconda3/envs/scn_cor
            shell level : 2
       user config file : /nfs/home/mfiruleva/.condarc
 populated config files : /nfs/home/mfiruleva/.condarc
          conda version : 4.8.3
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __glibc=2.27
       base environment : /nfs/home/mfiruleva/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-canary/linux-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /nfs/home/mfiruleva/anaconda3/pkgs
                          /nfs/home/mfiruleva/.conda/pkgs
       envs directories : /nfs/home/mfiruleva/anaconda3/envs
                          /nfs/home/mfiruleva/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-112-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 2178:1901
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.



  File "/nfs/home/mfiruleva/anaconda3/envs/scn_cor/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 318, in create
unlocking
removing lock
removing lock
removed all locks
